"""libraries

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-06 09:24:28.622134
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import reelhaven.db.types

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "libraries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "movies",
                "tv",
                "other",
                name="library_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("path", sa.String(length=4096), nullable=False),
        sa.Column("created_at", reelhaven.db.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", reelhaven.db.types.UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "type IN ('movies', 'tv', 'other')", name=op.f("ck_libraries_library_type")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_libraries")),
        sa.UniqueConstraint("name", name=op.f("uq_libraries_name")),
        sa.UniqueConstraint("path", name=op.f("uq_libraries_path")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("libraries")
    # ### end Alembic commands ###
