"""media files

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-06 10:53:15.551142
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import reelhaven.db.types

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(length=4096), nullable=False),
        sa.Column("relative_path", sa.String(length=4096), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("mtime_ns", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ok",
                "probe_failed",
                name="media_file_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("probe", sa.JSON(), nullable=True),
        sa.Column("probe_error", sa.Text(), nullable=True),
        sa.Column("first_seen_at", reelhaven.db.types.UTCDateTime(), nullable=False),
        sa.Column("last_seen_at", reelhaven.db.types.UTCDateTime(), nullable=False),
        sa.Column("probed_at", reelhaven.db.types.UTCDateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('ok', 'probe_failed')", name=op.f("ck_media_files_media_file_status")
        ),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
            name=op.f("fk_media_files_library_id_libraries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_files")),
        sa.UniqueConstraint("path", name=op.f("uq_media_files_path")),
    )
    with op.batch_alter_table("media_files", schema=None) as batch_op:
        batch_op.create_index(
            "ix_media_files_library_fingerprint", ["library_id", "fingerprint"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_media_files_library_id"), ["library_id"], unique=False)

    with op.batch_alter_table("libraries", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("last_scan_at", reelhaven.db.types.UTCDateTime(), nullable=True)
        )
        batch_op.add_column(sa.Column("last_scan_error", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("libraries", schema=None) as batch_op:
        batch_op.drop_column("last_scan_error")
        batch_op.drop_column("last_scan_at")

    with op.batch_alter_table("media_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_media_files_library_id"))
        batch_op.drop_index("ix_media_files_library_fingerprint")

    op.drop_table("media_files")
    # ### end Alembic commands ###
