"""integrations

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-06 11:12:32.853331
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import reelhaven.db.types

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "sonarr",
                "radarr",
                "tmdb",
                name="integration_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("base_url", sa.String(length=2048), nullable=False),
        sa.Column("api_key_encrypted", sa.Text(), nullable=False),
        sa.Column("verify_tls", sa.Boolean(), nullable=False),
        sa.Column("path_mappings", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", reelhaven.db.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", reelhaven.db.types.UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('sonarr', 'radarr', 'tmdb')", name=op.f("ck_integrations_integration_kind")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integrations")),
        sa.UniqueConstraint("name", name=op.f("uq_integrations_name")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("integrations")
    # ### end Alembic commands ###
