"""titles

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-06 11:18:29.481124
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import reelhaven.db.types

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "titles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("folder", sa.String(length=4096), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("original_language", sa.String(length=32), nullable=True),
        sa.Column(
            "language_source",
            sa.Enum(
                "sonarr",
                "radarr",
                "tmdb",
                "manual",
                "unknown",
                name="language_source",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_detail", sa.String(length=512), nullable=True),
        sa.Column("resolved_at", reelhaven.db.types.UTCDateTime(), nullable=True),
        sa.CheckConstraint(
            "language_source IN ('sonarr', 'radarr', 'tmdb', 'manual', 'unknown')",
            name=op.f("ck_titles_language_source"),
        ),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
            name=op.f("fk_titles_library_id_libraries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_titles")),
        sa.UniqueConstraint("library_id", "folder", name=op.f("uq_titles_library_id")),
    )
    with op.batch_alter_table("titles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_titles_library_id"), ["library_id"], unique=False)

    with op.batch_alter_table("media_files", schema=None) as batch_op:
        batch_op.add_column(sa.Column("title_id", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_media_files_title_id"), ["title_id"], unique=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_media_files_title_id_titles"),
            "titles",
            ["title_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("media_files", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_media_files_title_id_titles"), type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_media_files_title_id"))
        batch_op.drop_column("title_id")

    with op.batch_alter_table("titles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_titles_library_id"))

    op.drop_table("titles")
    # ### end Alembic commands ###
