"""library language policy

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-06 11:36:20.586256
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("libraries", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("language_policy", sa.JSON(), nullable=False, server_default=sa.text("'{}'"))
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("libraries", schema=None) as batch_op:
        batch_op.drop_column("language_policy")

    # ### end Alembic commands ###
