"""jobs and recycle bin

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-06 16:01:06.641936
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import reelhaven.db.types

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("media_file_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "verifying",
                "done",
                "failed",
                "cancelled",
                name="job_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("source_path", sa.String(length=4096), nullable=False),
        sa.Column("source_size", sa.Integer(), nullable=False),
        sa.Column("source_mtime_ns", sa.Integer(), nullable=False),
        sa.Column("plan", sa.JSON(), nullable=False),
        sa.Column("probe", sa.JSON(), nullable=False),
        sa.Column("progress", sa.Double(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("requested_by", sa.String(length=128), nullable=False),
        sa.Column("created_at", reelhaven.db.types.UTCDateTime(), nullable=False),
        sa.Column("started_at", reelhaven.db.types.UTCDateTime(), nullable=True),
        sa.Column("finished_at", reelhaven.db.types.UTCDateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'verifying', 'done', 'failed', 'cancelled')",
            name=op.f("ck_jobs_job_status"),
        ),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
            name=op.f("fk_jobs_library_id_libraries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["media_file_id"],
            ["media_files.id"],
            name=op.f("fk_jobs_media_file_id_media_files"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_library_id"), ["library_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_media_file_id"), ["media_file_id"], unique=False)
        batch_op.create_index("ix_jobs_status_priority", ["status", "priority", "id"], unique=False)

    op.create_table(
        "job_results",
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("bytes_before", sa.Integer(), nullable=False),
        sa.Column("bytes_after", sa.Integer(), nullable=False),
        sa.Column("duration_s", sa.Double(), nullable=True),
        sa.Column("process_seconds", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_results_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("job_id", name=op.f("pk_job_results")),
    )
    op.create_table(
        "recycle_bin",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("original_path", sa.String(length=4096), nullable=False),
        sa.Column("stored_path", sa.String(length=4096), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("created_at", reelhaven.db.types.UTCDateTime(), nullable=False),
        sa.Column("expires_at", reelhaven.db.types.UTCDateTime(), nullable=False),
        sa.Column("restored_at", reelhaven.db.types.UTCDateTime(), nullable=True),
        sa.Column("purged_at", reelhaven.db.types.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_recycle_bin_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
            name=op.f("fk_recycle_bin_library_id_libraries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recycle_bin")),
    )
    with op.batch_alter_table("recycle_bin", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recycle_bin_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_recycle_bin_library_id"), ["library_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recycle_bin", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recycle_bin_library_id"))
        batch_op.drop_index(batch_op.f("ix_recycle_bin_expires_at"))

    op.drop_table("recycle_bin")
    op.drop_table("job_results")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_jobs_status_priority")
        batch_op.drop_index(batch_op.f("ix_jobs_media_file_id"))
        batch_op.drop_index(batch_op.f("ix_jobs_library_id"))

    op.drop_table("jobs")
    # ### end Alembic commands ###
