"""profiles

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-06 20:41:30.946686
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import reelhaven.db.types

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("builtin", sa.Boolean(), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("created_at", reelhaven.db.types.UTCDateTime(), nullable=False),
        sa.Column("updated_at", reelhaven.db.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profiles")),
        sa.UniqueConstraint("name", name=op.f("uq_profiles_name")),
    )
    with op.batch_alter_table("libraries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("profile_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_libraries_profile_id_profiles"),
            "profiles",
            ["profile_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("libraries", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_libraries_profile_id_profiles"), type_="foreignkey")
        batch_op.drop_column("profile_id")

    op.drop_table("profiles")
    # ### end Alembic commands ###
