"""encode jobs

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-06 21:03:57.483858
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import reelhaven.db.types

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_results", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("outcome", sa.String(length=16), nullable=False, server_default="replaced")
        )
        batch_op.add_column(sa.Column("device", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("fps", sa.Double(), nullable=True))

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("profile", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("device", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("fps", sa.Double(), nullable=True))
        batch_op.add_column(sa.Column("speed", sa.Double(), nullable=True))

    with op.batch_alter_table("libraries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("test_run_profile", sa.String(length=32), nullable=True))
        batch_op.add_column(
            sa.Column("test_run_at", reelhaven.db.types.UTCDateTime(), nullable=True)
        )

    with op.batch_alter_table("media_files", schema=None) as batch_op:
        batch_op.add_column(sa.Column("no_gain_profile", sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("media_files", schema=None) as batch_op:
        batch_op.drop_column("no_gain_profile")

    with op.batch_alter_table("libraries", schema=None) as batch_op:
        batch_op.drop_column("test_run_at")
        batch_op.drop_column("test_run_profile")

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_column("speed")
        batch_op.drop_column("fps")
        batch_op.drop_column("device")
        batch_op.drop_column("profile")

    with op.batch_alter_table("job_results", schema=None) as batch_op:
        batch_op.drop_column("fps")
        batch_op.drop_column("device")
        batch_op.drop_column("outcome")

    # ### end Alembic commands ###
