"""test runs

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-07 07:07:43.937167
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import reelhaven.db.types

revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("profile", sa.JSON(), nullable=False),
        sa.Column("profile_fingerprint", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "done",
                "failed",
                "approved",
                name="test_run_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("requested_by", sa.String(length=128), nullable=False),
        sa.Column("created_at", reelhaven.db.types.UTCDateTime(), nullable=False),
        sa.Column("finished_at", reelhaven.db.types.UTCDateTime(), nullable=True),
        sa.Column("approved_by", sa.String(length=128), nullable=True),
        sa.Column("approved_at", reelhaven.db.types.UTCDateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'done', 'failed', 'approved')",
            name=op.f("ck_test_runs_test_run_status"),
        ),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
            name=op.f("fk_test_runs_library_id_libraries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_runs")),
    )
    with op.batch_alter_table("test_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_test_runs_library_id"), ["library_id"], unique=False)

    op.create_table(
        "test_run_samples",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("test_run_id", sa.Integer(), nullable=False),
        sa.Column("media_file_id", sa.Integer(), nullable=True),
        sa.Column("relative_path", sa.String(length=4096), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "done",
                "failed",
                name="test_sample_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("finished_at", reelhaven.db.types.UTCDateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'done', 'failed')",
            name=op.f("ck_test_run_samples_test_sample_status"),
        ),
        sa.ForeignKeyConstraint(
            ["media_file_id"],
            ["media_files.id"],
            name=op.f("fk_test_run_samples_media_file_id_media_files"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["test_runs.id"],
            name=op.f("fk_test_run_samples_test_run_id_test_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_run_samples")),
    )
    with op.batch_alter_table("test_run_samples", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_test_run_samples_test_run_id"), ["test_run_id"], unique=False
        )

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("test_run_sample_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_jobs_test_run_sample_id_test_run_samples"),
            "test_run_samples",
            ["test_run_sample_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("libraries", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("test_run_samples", sa.Integer(), server_default="1", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("libraries", schema=None) as batch_op:
        batch_op.drop_column("test_run_samples")

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_jobs_test_run_sample_id_test_run_samples"), type_="foreignkey"
        )
        batch_op.drop_column("test_run_sample_id")

    with op.batch_alter_table("test_run_samples", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_run_samples_test_run_id"))

    op.drop_table("test_run_samples")
    with op.batch_alter_table("test_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_runs_library_id"))

    op.drop_table("test_runs")
    # ### end Alembic commands ###
