"""library watch mode

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-07 17:20:15.443820
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("libraries", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "watch_mode",
                sa.Enum(
                    "off",
                    "watch",
                    "automatic",
                    name="watch_mode",
                    native_enum=False,
                    create_constraint=True,
                ),
                server_default="off",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("libraries", schema=None) as batch_op:
        batch_op.drop_column("watch_mode")

    # ### end Alembic commands ###
